### ISSUE TITLE
Weblink Field plugin removed all slash in url value

### ISSUE THREAD

**Issue by desbear** [FLEXIcontent/flexicontent-cck#822] opened 2017-12-20 02:57 UTC
![2017-12-20 10 56 18](https://user-images.githubusercontent.com/545068/34189030-7481b7b4-e574-11e7-9236-3c3f95158bba.png)
FC 3.2.1.7 Joomla 3.8.2

**Comment by ggppdk** [comment] 2017-12-20 10:23
Please go to Joomla extension manager and use 
Install via URL:
https://github.com/FLEXIcontent/flexicontent-cck/archive/3.2.1.x-stable.zip

**Comment by ldoliv** [comment] 2018-01-30 09:07
I can confirm this is not working on the 3.2.1.x-stable release. Please fix.

**Comment by ggppdk** [comment] 2018-01-30 18:19
I cannot confirm the issue with v3.2.1.10 or with current 3.2.1.x-stable branch

@desbear 
@ldoliv 

Since this may depend **on some specific configuration**

Please contact me with PM (Private me) in our forum with access to website
and some small instruction on how to view the issue
e.g. edit item NNN and at field name "name" the slashes are removed

**Comment by ldoliv** [comment] 2018-01-31 09:04
Before:
![image](https://user-images.githubusercontent.com/6535818/35614039-9fb3c514-0665-11e8-95ab-23f312be2ae8.png)

After:
![image](https://user-images.githubusercontent.com/6535818/35614055-b0c10704-0665-11e8-8da6-fa49f35efd20.png)

**Comment by ggppdk** [comment] 2018-01-31 14:31
Yes,
```php
JUri::root(true) . '/'
```
evaluates to just slash when Joomla is not in a subfolder
thus all slashes will be stripped if you enter a URL that starts with slash

Fixed with 358355976

Please use install via URL in extension manager to install in a test site to test, or just copy the updated weblink.php
https://github.com/FLEXIcontent/flexicontent-cck/archive/3.2.1.x-stable.zip

**Comment by ldoliv** [comment] 2018-01-31 14:44
Ok. It only strips the first slash now.

But I ask, is is correct to strip the first slash ?

**Comment by ggppdk** [comment] 2018-01-31 18:48
> It must not strip any slashes, how do I reference the root of the site without indicating an absolute path?

that is correct, and that is our intended behaviour , the URL must be made relative
and you do not need to worry of Joomla root it will be added automatically !

Let me explain, **if it is configured to be relative** 
- then it does not just strip the "first slash" 

it strips the joomla installation subfolder to make it relative !!

e.g. Joomla subfolder /joomla384test/
URL
/joomla384test/menu-alias1/menu-alias2/something.html

becomes relative:
menu-alias1/menu-alias2/something.html

thus when you move website e.g. to ROOT folder it will continue to work !!

in you case there is no joomla subfolder , so instead of
 /joomla384test/
you just have /
so it is stripped and URL becomes relative

**Closed by ggppdk** 2018-01-31 18:48 UTC
Labels: Priority Normal, bug
