### ISSUE TITLE
Select Multiple field - bug when "Sortable" is enabled

### ISSUE THREAD

**Issue by lyquix-owner** [FLEXIcontent/flexicontent-cck#762] opened 2017-08-17 20:58 UTC
Hello,

We have noticed a bug in the Select Multiple field, when the option "Sortable" is enabled:

The first time the item form is loaded, and the field has no values, it works fine. After saving, when the field has values, the first value is repeated after every other value.

After some research we identified that is caused by improperly handling the `data-select2-initdata` parameter. We implemented a quick solution by editing `administrator/components/com_flexicontent/helpers/fcfield/indexedfield.php` line 672 adding the following code:

```
if (strrpos($attribs, 'data-select2-initdata'))
	$attribs = substr($attribs, 0, strrpos($attribs, 'data-select2-initdata'));
```

This is not very elegant, but it works. Maybe it is better to improve the logic upstream.

**Comment by ggppdk** [comment] 2017-08-18 04:53
I can not replicate this

i think you have some extra JS code that is running and is causing this

**Comment by lyquix-owner** [comment] 2017-08-18 14:37
Please ignore my description of the problem, I realize I didn't explain correctly and missed a couple details. Here I go again:   :-)

Follow the steps to reproduce the error:

- Create a Select Multiple field with the following settings
  -  Allow multiple values: Yes
  - Apply JS Library: Select2
  - Sortable: Yes
  - Add test options: A, B, C, D, E
- Create a new item that includes the new field
- Select options A, B, and C
- Add a new field value
- You can see that the options selected from the first value are repeated (Bug)
- Change the options in the second field to be E,D,C
- Save/Apply Item
- Field show options correctly
- Save and Close
- Open item again
- Fields don't show correct information, the options of the first value are repeated on the second value (Bug)

**Comment by ggppdk** [comment] 2017-08-18 15:20
The problem is that we are getting multiple, 
data-select2-initdata="..."
(your fix is working because it is removing the previous value of the attribute)

thus first value has
data-select2-initdata="..."

2nd value
data-select2-initdata="..." data-select2-initdata="..."

3rd value
data-select2-initdata="..." data-select2-initdata="..." data-select2-initdata="..."

This particular attribute was supposed to be per value, unlike the other attributes e.g. data-max-values which is same for all fields

Fixed it with: 838ca00 , tested it and it is proper now

Fix is easy to apply in v3.2.0.1 or you can use current github branch of v3.2.x-stable 
After you test fix i will close this issue

**Comment by lyquix-owner** [comment] 2017-08-18 15:30
Wonderful! Thank you! I confirm the fix works

**Comment by ggppdk** [comment] 2017-08-18 15:47
Nice , thanks

**Closed** 2017-08-18 15:47 UTC
