### ISSUE TITLE
Upload images on IE Edge

### ISSUE THREAD

**Issue by tevez15** [FLEXIcontent/flexicontent-cck#776] opened 2017-09-15 08:41 UTC
Hello,

I have a problem to upload files, using drag or add file on Edge. He dont do nothing.

![image](https://user-images.githubusercontent.com/6087425/30473950-f69fd0ee-99f9-11e7-9a24-02f86e9d971d.png)

The same using upload by clicking on "My Files"

Can you check? Thank you

**Comment by ggppdk** [comment] 2017-09-15 09:35
So the issue is that drag and drop is not working in Edge browesr 
- but using Add files button is working properly, correct ?

**Comment by tevez15** [comment] 2017-09-15 10:03
No, nothing work :\

**Comment by ggppdk** [comment] 2017-09-15 11:04
I tested with Edge and drag and drop is working in inline uploader mode

But clicking on the "Add images" is not opening the file selection window

**Comment by ggppdk** [comment] 2017-09-15 11:28
Ok tested with IE8 - IE11 everything works

With edge the drag and drop is working
but clicking on buttons "Add images" or "Upload images"

probably we need to update from plupload v2.1.9 to plupload v2.3.3

**Comment by tevez15** [comment] 2017-09-15 11:29
OK, thank you :)

**Comment by ggppdk** [comment] 2017-09-15 11:46
Fixed with 9a8f236

Updated plupload JS to v2.3.3

**Closed by ggppdk** 2017-09-15 11:46 UTC
